blog/urls.py
from django.conf.urls import url
from . import views

# 正则匹配链接中的字符，调用view中的函数，返回对应链接
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),  # 主页
    url(r'index.html$', views.index, name='index'),  # HOME
    url(r'contact.html$', views.contact, name='contact'),  # Contact
    url(r'about.html$', views.about, name='about'),  # About
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),  # 详情页
    # 例如如果用户访问 /archives/2017/3/，那么 archives 视图函数的实际调用为：archives(request, year=2017, month=3)
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),  # 归档页
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),  # 分类页，用PK值对应分类
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^blog/', include('blog.urls'),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]
# 简单说 name 可以用于在 templates, models, views ……中得到对应的网址，
# 相当于“给网址取了个名字，只要这个名字不变，网址变了也能通过名字获取到。
# 尽可能的把应用本身的URL部署到内部，在这里做一个总的引用。

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    """
    django 要求我们必须继承 models.Model 类，
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了 name 的数据类型，CharField 是字符型，
    max_length 指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '类别'
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段比较多。
    """
    # 文章标题
    title = models.CharField(max_length=70)

    # 文章正文，我们使用了 TextField。比较短的字符串存储可以使用 CharField，
    # 但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分表表示了文章的创建时间和最后一次修改时间，存储时间的列用 DateTimeField。
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，
    # 否则就会报错。指定 blank=True 后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True)
    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类与标签对应的表关联起来，
    # 但是关联形式稍微有点不同。我们规定一篇文章只能对应一个分类，
    # 但是一个分类下可以有很多篇文章，所以我们使用的是 ForeignKey，
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    # 文章作者这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，专门用于处理网站用户的注册、登录等流程，
    # User 是 django 为我们已经写好的用户模型，
    # 这里我们通过 ForeignKey 把文章和 User 关联起来，
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章
    # 因此这是一对多的关系，和 Category 类似。
    author = models.ForeignKey(User)

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name

comments/models.py
from django.db import models


# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

comments/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': "名字",
            }),
            'email': forms.TextInput(attrs={
                'placeholder': "邮箱",
            }),
            'url': forms.TextInput(attrs={
                'placeholder': "网址",
            }),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
import markdown
from comments.forms import CommentForm


# 主页
def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 详情页
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {'post': post,
               'form': form,
               'comment_list': comment_list
               }
    return render(request, 'blog/detail.html', context=context)


# contact
def contact(request):
    return render(request, 'blog/contact.html')


# about
def about(request):
    return render(request, 'blog/about.html')


# 跳转到归档的主页
def archives(request, year, month):
    # 更换主页文章列表为按月显示
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 分类页
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

comments/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

from .models import Comment
from .forms import CommentForm


def post_comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来
    # 使用了 django 提供的一个快捷函数 get_object_or_404
    # 当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户
    post = get_object_or_404(Post, pk=post_pk)

    # http 请求有 get 和 post 两种方法，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据
    if request.method == 'POST':
        # 用户提交的数据存在 request.POST
        # 我们利用这些数据构造了 CommentForm 的实例，这样 django 的表单就生成了
        form = CommentForm(request.POST)

        # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求
        if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例
            # 但还不保存数据到数据库
            comment = form.save(commit=False)
            # 将评论和被评论的文章关联起来
            comment.post = post
            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            comment.save()

            # 重定向到 post 的详情页
            return redirect(post)

        else:
            # 检查到数据不合法，重新渲染详情页，并且渲染表单的错误
            # 因此我们传了三个模板变量给 detail.html
            # 一个是文章（Post），一个是评论列表，一个是表单 form
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)
    # 不是 post 请求，重定向到文章详情页。
    return redirect(post)

templates/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html>
	<head>
		<title>Marmot的博客</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}

	    <!-- css -->
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css'%}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/friendly.css' %}">

	    <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body>
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
                            <h1><a href="index.html">~Welcom~</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="https://github.com/Marmot93" data-hover="GitHub" target="_blank">GitHub</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
		<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
                        {% block main %}
                        {% endblock main %}
					</main>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">
							<h3 class="widget-title">最新文章</h3>
                            {% get_recent_posts as recent_post_list %}
							<ul>
                                {% for post in recent_post_list %}
								<li>
									<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
								</li>
								{% endfor %}
							</ul>
						</div>
						<div class="widget widget-archives">
							<h3 class="widget-title">归档</h3>
                            {% archives as date_list %}
							<ul>
                                {% for date in date_list %}
								<li>
									<a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
								</li>
                                {% endfor %}
							</ul>
						</div>

						<div class="widget widget-category">
							<h3 class="widget-title">分类</h3>
                            {% get_categories as category_list %}
							<ul>
                                {% for category in category_list %}
								<li>
									<a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
								</li>
                                {% endfor %}
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2017 Marmot <a href="https://github.com/Marmot93" target="_blank" title="GitHub">GitHub链接</a></p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="">Home</a></li>
					<li class="cl-effect-11"><a href="https://github.com/Marmot93" data-hover="GitHub" target="_blank">GitHub</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>

	</body>
</html>

templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>About Me</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}

	    <!-- css -->
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css'%}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

	    <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html">About Me</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="https://github.com/Marmot93" data-hover="GitHub" target="_blank">GitHub</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="http://cdn.hopyun.com/20130628185346_T5PSW.thumb.600_0.jpeg" alt="Developer Image">
                                    <!--<img class="img-responsive" src="{% static 'blog/img/test4.png' %}" alt="Developer Image">-->
                                </figure>
								<p>
                                    也不知道为什么，一直以来都喜欢解决问题，但是呢，并没有多少人相信。
                                </p>
                                <p>
                                    总是渴望去做一些可以提高自己的事情，似乎只有这样生命才不会被浪费。
                                </p>
                                <p>
                                    发现问题从不逃避，解决问题毫不犹豫，最主要的当然是最后成功解决问题的时候的成就感。</p>
                                <p>
                                    本来当老师也是好好的，帮助别人解决问题，看着自己的学生进步了，由衷的高兴。
                                    做老师这么两年，最大的成就可能就是敢说：我带过的学生没有不进步的。深知转行很难，但是如果现在不追求一下，
                                    后半生一定会憎恨自己吧。都是肩膀上一个脑袋，别人能行，我也可以！
                                </p>
                                <p>
                                    "吾生也有涯，而知也无涯。以有涯随无涯，殆已！"很多人嘲笑老师只交给我们第一句，忽略了后面一句，但是，
                                    明知道求知之路是危险的，难道就要放弃了么？stay hungry stay foolish。
                                </p>
                                <p>
                                    对于朋友圈都不怎么发的我，写这么多娇情的话，也算是给这个博客留下一个小彩蛋吧。姑且认为点了About的人是愿意
                                    了解我的人，而不是这个现在还很粗糙的博客，相信它也会和我一路，风雨同行。
                                </p>
                                <p align="right">2017-4-14 00:13</p>
								<div class="height-40px"></div>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2017 Marmot</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li class="cl-effect-11"><a href="https://github.com/Marmot93" data-hover="GitHub" target="_blank">GitHub</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Contact</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}

	    <!-- css -->
		<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css'%}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

	    <!-- js -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html">Contact Me</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="https://github.com/Marmot93" data-hover="GitHub" target="_blank">GitHub</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">～联系我～</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
                                        <p align="center">需要联系我或者有什么问题都可以给我发电子邮件哦，我会定期查看并回复</p>
										<p align="center">Email:654332905@qq.com</p>
                                        <center><img src="http://cdn.hopyun.com/1d4a28d8f2d91e37.jpg" ></center>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2017 Marmot</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li class="cl-effect-11"><a href="https://github.com/Marmot93" data-hover="GitHub" target="_blank">GitHub</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <hr/>
    <h2>文章区</h2>
    <hr/>
    <article class="post post-1">
        <header class="entry-header">

            <h1 class="entry-title">
                {{ post.title }}
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>

                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>

                <span class="post-author"><a href="#">{{ post.author }}</a></span>

                <span class="comments-link"><a href="#">4 Comments</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>

    <!-- 分割线，以下为评论区 -->
    <hr/>
    <h2>评论区</h2>
    <hr/>

    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.name.id_for_label }}">Name:</label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">Email:</label>
      {{ form.email }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">Url:</label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">Comment:</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit"><span>提交评论</span></button>
    </div>
  </div>    <!-- row -->
</form>
    <div class="comment-list">
  <h3>评论列表</h3>
  <ul class="list-unstyled">
    {% for comment in comment_list %}
    <li class="comment-item">
      <span class="name">{{ comment.name }}</span>
      <time class="date">{{ comment.created_time }}</time>
      <div class="text">
        {{ comment.text }}
      </div>
    </li>
    {% empty %}
    暂无评论
    {% endfor %}
  </ul>
</div>
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}" >{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>

                    <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>

                    <span class="post-author"><a href="#">{{ post.author }}</a></span>

                    <span class="comments-link"><a href="#">4 Comments</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link" >继续阅读<span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}